#!/usr/bin/env python3
"""
Generate PET B1 vocabulary files
"""

import os
from typing import List, Dict, Any

def create_word_entry(word: str, pos: str, definition_en: str, meaning_zh: str, 
                      example: str, example_zh: str, topic: str, difficulty: int) -> Dict[str, Any]:
    """Create a word entry dictionary"""
    return {
        'word': word,
        'partOfSpeech': pos,
        'simpleDefinitionEn': definition_en,
        'meaningZh': meaning_zh,
        'exampleSentence': example,
        'exampleSentenceZh': example_zh,
        'topicTag': topic,
        'difficulty': difficulty
    }

def generate_abstract_words() -> List[Dict[str, Any]]:
    """Generate abstract concept words"""
    words = [
        create_word_entry('idea', 'noun', 'a thought or suggestion', '想法，主意', 
                         'I have a good idea for our project.', '我对我们的项目有个好主意。', 'abstract', 1),
        create_word_entry('reason', 'noun', 'why something happens or exists', '原因，理由',
                         'The reason for the delay is bad weather.', '延误的原因是天气不好。', 'abstract', 1),
        create_word_entry('result', 'noun', 'what happens because of something', '结果',
                         'The test results will be ready tomorrow.', '测试结果明天会准备好。', 'abstract', 1),
        create_word_entry('method', 'noun', 'a way of doing something', '方法',
                         'This is a new method for learning languages.', '这是一种学习语言的新方法。', 'abstract', 2),
        create_word_entry('system', 'noun', 'a set of connected things that work together', '系统',
                         'The school has a good grading system.', '学校有一个好的评分系统。', 'abstract', 2),
        create_word_entry('rule', 'noun', 'what you must or must not do', '规则',
                         'Follow the rules of the game.', '遵守游戏规则。', 'abstract', 1),
        create_word_entry('law', 'noun', 'official rules of a country', '法律',
                         'It is against the law to steal.', '偷窃是违法的。', 'abstract', 2),
        create_word_entry('principle', 'noun', 'a basic idea or rule', '原则',
                         'Honesty is an important principle.', '诚实是一个重要的原则。', 'abstract', 3),
        create_word_entry('theory', 'noun', 'an idea that explains something', '理论',
                         'Einstein developed the theory of relativity.', '爱因斯坦发展了相对论。', 'abstract', 3),
        create_word_entry('fact', 'noun', 'something that is true', '事实',
                         'It is a fact that the Earth is round.', '地球是圆的，这是一个事实。', 'abstract', 1),
        create_word_entry('truth', 'noun', 'what is true', '真相，真理',
                         'Always tell the truth.', '永远要说真话。', 'abstract', 2),
        create_word_entry('opinion', 'noun', 'what someone thinks about something', '观点，意见',
                         'In my opinion, this is the best solution.', '在我看来，这是最好的解决方案。', 'abstract', 1),
        create_word_entry('belief', 'noun', 'something you think is true', '信念，信仰',
                         'Religious beliefs are important to many people.', '宗教信仰对很多人很重要。', 'abstract', 2),
        create_word_entry('value', 'noun', 'how important something is', '价值',
                         'Family values are important in our culture.', '家庭价值观在我们的文化中很重要。', 'abstract', 2),
        create_word_entry('purpose', 'noun', 'why something exists or is done', '目的',
                         'The purpose of this meeting is to plan the project.', '这次会议的目的是规划项目。', 'abstract', 2),
        create_word_entry('goal', 'noun', 'something you want to achieve', '目标',
                         'My goal is to learn English fluently.', '我的目标是流利地学习英语。', 'abstract', 1),
        create_word_entry('aim', 'noun', 'what you want to achieve', '目标，目的',
                         'The aim of this exercise is to improve fitness.', '这个练习的目的是提高体能。', 'abstract', 2),
        create_word_entry('plan', 'noun', 'what you will do in the future', '计划',
                         'We need a plan for the weekend.', '我们需要一个周末计划。', 'abstract', 1),
        create_word_entry('strategy', 'noun', 'a plan to achieve something', '策略',
                         'The company has a new marketing strategy.', '公司有一个新的营销策略。', 'abstract', 3),
        create_word_entry('process', 'noun', 'a series of actions to achieve something', '过程',
                         'Learning a language is a long process.', '学习语言是一个漫长的过程。', 'abstract', 2),
        create_word_entry('effect', 'noun', 'a change that something causes', '效果，影响',
                         'The medicine had a positive effect.', '药物有积极的效果。', 'abstract', 2),
        create_word_entry('influence', 'noun', 'power to affect someone or something', '影响',
                         'Parents have a big influence on children.', '父母对孩子有很大的影响。', 'abstract', 2),
        create_word_entry('difference', 'noun', 'how things are not the same', '差异，不同',
                         'There is a big difference between these two options.', '这两个选项有很大的不同。', 'abstract', 1),
        create_word_entry('similarity', 'noun', 'how things are the same', '相似性',
                         'There are many similarities between the two languages.', '这两种语言有很多相似之处。', 'abstract', 2),
        create_word_entry('advantage', 'noun', 'something good about a situation', '优势，优点',
                         'One advantage of living in the city is good transport.', '住在城市的一个优势是交通便利。', 'abstract', 2),
        create_word_entry('disadvantage', 'noun', 'something bad about a situation', '劣势，缺点',
                         'The disadvantage of this plan is the cost.', '这个计划的缺点是成本。', 'abstract', 2),
        create_word_entry('benefit', 'noun', 'something good that helps you', '好处，益处',
                         'Exercise has many health benefits.', '锻炼有很多健康益处。', 'abstract', 2),
        create_word_entry('harm', 'noun', 'damage or injury', '伤害',
                         'Smoking can cause serious harm to your health.', '吸烟会对你的健康造成严重伤害。', 'abstract', 2),
        create_word_entry('risk', 'noun', 'chance of something bad happening', '风险',
                         'There is a risk of rain tomorrow.', '明天有下雨的风险。', 'abstract', 2),
        create_word_entry('danger', 'noun', 'possibility of harm or death', '危险',
                         'Be careful, there is danger ahead.', '小心，前面有危险。', 'abstract', 1),
        create_word_entry('safety', 'noun', 'being safe from danger', '安全',
                         'Safety is our first priority.', '安全是我们的首要任务。', 'abstract', 1),
        create_word_entry('chance', 'noun', 'possibility that something will happen', '机会，可能性',
                         'There is a good chance of success.', '成功的机会很大。', 'abstract', 1),
        create_word_entry('opportunity', 'noun', 'a good chance to do something', '机会',
                         'This job is a great opportunity for me.', '这份工作对我来说是一个很好的机会。', 'abstract', 2),
        create_word_entry('possibility', 'noun', 'something that might happen', '可能性',
                         'There is a possibility of snow tonight.', '今晚有可能下雪。', 'abstract', 2),
        create_word_entry('probability', 'noun', 'how likely something is to happen', '概率',
                         'The probability of winning is very low.', '获胜的概率非常低。', 'abstract', 3),
        create_word_entry('condition', 'noun', 'the state something is in', '条件，状况',
                         'The car is in excellent condition.', '这辆车状况极佳。', 'abstract', 2),
        create_word_entry('situation', 'noun', 'what is happening at a particular time', '情况，形势',
                         'We need to understand the situation better.', '我们需要更好地了解情况。', 'abstract', 1),
        create_word_entry('circumstance', 'noun', 'facts or events that affect a situation', '环境，情况',
                         'Under normal circumstances, this would not happen.', '在正常情况下，这不会发生。', 'abstract', 3),
        create_word_entry('problem', 'noun', 'something difficult that needs to be solved', '问题',
                         'We have a problem with the computer.', '我们的电脑有问题。', 'abstract', 1),
        create_word_entry('solution', 'noun', 'a way to solve a problem', '解决方案',
                         'We need to find a solution to this issue.', '我们需要找到这个问题的解决方案。', 'abstract', 2),
        create_word_entry('answer', 'noun', 'what you say when someone asks a question', '答案',
                         'Do you know the answer to this question?', '你知道这个问题的答案吗？', 'abstract', 1),
        create_word_entry('question', 'noun', 'what you ask when you want information', '问题',
                         'I have a question about the homework.', '我有一个关于作业的问题。', 'abstract', 1),
        create_word_entry('choice', 'noun', 'act of choosing between things', '选择',
                         'You have a choice between tea and coffee.', '你可以在茶和咖啡之间选择。', 'abstract', 1),
        create_word_entry('option', 'noun', 'something you can choose', '选项',
                         'We have several options for dinner.', '我们有几个晚餐选项。', 'abstract', 2),
        create_word_entry('alternative', 'noun', 'another possibility', '替代方案',
                         'We need to consider an alternative plan.', '我们需要考虑一个替代计划。', 'abstract', 3),
        create_word_entry('decision', 'noun', 'choice you make after thinking', '决定',
                         'I need to make a decision by tomorrow.', '我需要在明天之前做出决定。', 'abstract', 1),
        create_word_entry('agreement', 'noun', 'when people have the same opinion', '协议，同意',
                         'We reached an agreement on the price.', '我们就价格达成了协议。', 'abstract', 2),
        create_word_entry('disagreement', 'noun', 'when people have different opinions', '分歧，不同意',
                         'There was a disagreement about the plan.', '关于这个计划存在分歧。', 'abstract', 2),
        create_word_entry('argument', 'noun', 'angry discussion between people', '争论，论点',
                         'They had an argument about money.', '他们因为钱发生了争论。', 'abstract', 2),
        create_word_entry('discussion', 'noun', 'talking about something seriously', '讨论',
                         'We need to have a discussion about this.', '我们需要讨论一下这个问题。', 'abstract', 1),
        create_word_entry('conclusion', 'noun', 'final part or decision', '结论',
                         'In conclusion, I think we should accept the offer.', '总之，我认为我们应该接受这个提议。', 'abstract', 2),
    ]
    return words

def generate_communication_words() -> List[Dict[str, Any]]:
    """Generate communication words"""
    words = [
        create_word_entry('say', 'verb', 'to speak words', '说',
                         'What did you say?', '你说了什么？', 'communication', 1),
        create_word_entry('tell', 'verb', 'to give information to someone', '告诉',
                         'Tell me your name.', '告诉我你的名字。', 'communication', 1),
        create_word_entry('ask', 'verb', 'to put a question to someone', '问',
                         'May I ask you a question?', '我可以问你一个问题吗？', 'communication', 1),
        create_word_entry('answer', 'verb', 'to reply to a question', '回答',
                         'Please answer the question.', '请回答问题。', 'communication', 1),
        create_word_entry('explain', 'verb', 'to make something clear', '解释',
                         'Can you explain how this works?', '你能解释一下这是如何工作的吗？', 'communication', 2),
        create_word_entry('describe', 'verb', 'to say what something is like', '描述',
                         'Describe what you saw.', '描述你看到的东西。', 'communication', 2),
        create_word_entry('announce', 'verb', 'to tell people something officially', '宣布',
                         'They will announce the winner tomorrow.', '他们明天将宣布获胜者。', 'communication', 2),
        create_word_entry('report', 'verb', 'to give information about something', '报告',
                         'I need to report the problem to my boss.', '我需要向老板报告这个问题。', 'communication', 2),
        create_word_entry('state', 'verb', 'to say something clearly', '陈述',
                         'He stated his opinion clearly.', '他清楚地陈述了自己的观点。', 'communication', 2),
        create_word_entry('express', 'verb', 'to show what you think or feel', '表达',
                         'It\'s important to express your feelings.', '表达你的感受很重要。', 'communication', 2),
        create_word_entry('mention', 'verb', 'to speak about something briefly', '提到',
                         'He mentioned your name in the meeting.', '他在会议上提到了你的名字。', 'communication', 2),
        create_word_entry('suggest', 'verb', 'to give an idea for consideration', '建议',
                         'I suggest we take a break.', '我建议我们休息一下。', 'communication', 2),
        create_word_entry('advise', 'verb', 'to give advice to someone', '建议，劝告',
                         'The doctor advised me to rest.', '医生建议我休息。', 'communication', 2),
        create_word_entry('warn', 'verb', 'to tell someone about danger', '警告',
                         'I warned him about the risks.', '我警告过他风险。', 'communication', 2),
        create_word_entry('promise', 'verb', 'to say you will definitely do something', '承诺',
                         'I promise to help you.', '我承诺帮助你。', 'communication', 1),
        create_word_entry('refuse', 'verb', 'to say you will not do something', '拒绝',
                         'He refused to answer the question.', '他拒绝回答问题。', 'communication', 2),
        create_word_entry('deny', 'verb', 'to say something is not true', '否认',
                         'She denied the accusation.', '她否认了指控。', 'communication', 2),
        create_word_entry('admit', 'verb', 'to agree that something is true', '承认',
                         'He admitted his mistake.', '他承认了自己的错误。', 'communication', 2),
        create_word_entry('claim', 'verb', 'to say something is true', '声称',
                         'He claims to have seen a UFO.', '他声称看到了不明飞行物。', 'communication', 2),
        create_word_entry('argue', 'verb', 'to give reasons for your opinion', '争论，论证',
                         'They argued about politics.', '他们争论政治问题。', 'communication', 2),
        create_word_entry('persuade', 'verb', 'to make someone agree with you', '说服',
                         'I tried to persuade him to come.', '我试图说服他来。', 'communication', 3),
        create_word_entry('convince', 'verb', 'to make someone believe something', '使信服',
                         'She convinced me to change my mind.', '她说服我改变了主意。', 'communication', 3),
        create_word_entry('encourage', 'verb', 'to give support or confidence', '鼓励',
                         'My teacher encouraged me to study harder.', '我的老师鼓励我更加努力学习。', 'communication', 2),
        create_word_entry('praise', 'verb', 'to say good things about someone', '表扬',
                         'The boss praised her work.', '老板表扬了她的工作。', 'communication', 2),
        create_word_entry('criticize', 'verb', 'to say what is wrong with something', '批评',
                         'Don\'t criticize others without reason.', '不要无故批评他人。', 'communication', 2),
        create_word_entry('complain', 'verb', 'to say you are not happy about something', '抱怨',
                         'Customers often complain about the service.', '顾客经常抱怨服务。', 'communication', 2),
        create_word_entry('apologize', 'verb', 'to say sorry', '道歉',
                         'I apologize for being late.', '我为迟到道歉。', 'communication', 2),
        create_word_entry('forgive', 'verb', 'to stop being angry with someone', '原谅',
                         'Please forgive me for my mistake.', '请原谅我的错误。', 'communication', 2),
        create_word_entry('thank', 'verb', 'to say thank you', '感谢',
                         'I want to thank you for your help.', '我想感谢你的帮助。', 'communication', 1),
        create_word_entry('greet', 'verb', 'to say hello to someone', '问候',
                         'She greeted me with a smile.', '她微笑着问候我。', 'communication', 1),
        create_word_entry('introduce', 'verb', 'to tell people each other\'s names', '介绍',
                         'Let me introduce you to my friend.', '让我把你介绍给我的朋友。', 'communication', 2),
        create_word_entry('invite', 'verb', 'to ask someone to come somewhere', '邀请',
                         'I want to invite you to my party.', '我想邀请你参加我的派对。', 'communication', 1),
        create_word_entry('offer', 'verb', 'to say you will give something', '提供',
                         'He offered to help me.', '他提出要帮助我。', 'communication', 2),
        create_word_entry