import { SentenceCard } from 'shared-types';

export const comparisonSentences: Omit<SentenceCard, 'id' | 'memoryState' | 'intervalDays' | 
  'nextReviewAt' | 'lapseCount' | 'correctCount' | 'wrongCount' | 
  'lastReviewedAt' | 'createdAt' | 'updatedAt'>[] = [
  // Both/Neither
  { sentence:'Both my brother and I enjoy swimming.', sentenceZh:'我和我弟弟都喜欢游泳。', chunkList:['Both','my brother and I','enjoy','swimming','.'], keyPhrases:['Both','my brother and I','enjoy swimming'], functionTag:'comparison_both', topicTag:'writing', difficulty:2 },
  { sentence:'Neither option is perfect.', sentenceZh:'两个选项都不完美。', chunkList:['Neither option','is','perfect','.'], keyPhrases:['Neither option','perfect'], functionTag:'comparison_neither', topicTag:'writing', difficulty:2 },
  { sentence:'We can both speak English and French.', sentenceZh:'我们都会说英语和法语。', chunkList:['We can both','speak','English and French','.'], keyPhrases:['both','speak','English and French'], functionTag:'comparison_both', topicTag:'speaking', difficulty:2 },
  { sentence:'Neither of us has been there before.', sentenceZh:'我们俩都没去过那里。', chunkList:['Neither of us','has been','there before','.'], keyPhrases:['Neither of us','has been','before'], functionTag:'comparison_neither', topicTag:'speaking', difficulty:3 },
  { sentence:'Both cities have their own charm.', sentenceZh:'两个城市都有各自的魅力。', chunkList:['Both cities','have','their own charm','.'], keyPhrases:['Both cities','their own charm'], functionTag:'comparison_both', topicTag:'writing', difficulty:2 },
  { sentence:'I like neither coffee nor tea.', sentenceZh:'我既不喜欢咖啡也不喜欢茶。', chunkList:['I like','neither coffee','nor tea','.'], keyPhrases:['neither','nor'], functionTag:'comparison_neither', topicTag:'speaking', difficulty:3 },
  { sentence:'Both the book and the movie were excellent.', sentenceZh:'书和电影都很棒。', chunkList:['Both','the book and the movie','were','excellent','.'], keyPhrases:['Both','book and movie','excellent'], functionTag:'comparison_both', topicTag:'writing', difficulty:2 },
  { sentence:'Neither answer is correct.', sentenceZh:'两个答案都不正确。', chunkList:['Neither answer','is','correct','.'], keyPhrases:['Neither answer','correct'], functionTag:'comparison_neither', topicTag:'writing', difficulty:2 },
  { sentence:'We both agree on this point.', sentenceZh:'我们俩都同意这一点。', chunkList:['We both','agree','on this point','.'], keyPhrases:['both agree','on this point'], functionTag:'comparison_both', topicTag:'speaking', difficulty:2 },
  { sentence:'Neither solution seems practical.', sentenceZh:'两种解决方案似乎都不实用。', chunkList:['Neither solution','seems','practical','.'], keyPhrases:['Neither solution','practical'], functionTag:'comparison_neither', topicTag:'writing', difficulty:3 },
  
  // whereas/while
  { sentence:'Whereas London is busy, Edinburgh is more relaxed.', sentenceZh:'伦敦很繁忙，而爱丁堡更放松。', chunkList:['Whereas','London is busy',',','Edinburgh is','more relaxed','.'], keyPhrases:['Whereas','busy','more relaxed'], functionTag:'comparison_whereas', topicTag:'writing', difficulty:3 },
  { sentence:'While some people love winter, others prefer summer.', sentenceZh:'有些人喜欢冬天，而其他人更喜欢夏天。', chunkList:['While','some people love winter',',','others prefer','summer','.'], keyPhrases:['While','love winter','prefer summer'], functionTag:'comparison_while', topicTag:'writing', difficulty:3 },
  { sentence:'He enjoys sports, whereas his brother prefers reading.', sentenceZh:'他喜欢运动，而他弟弟更喜欢阅读。', chunkList:['He enjoys sports',',','whereas','his brother prefers','reading','.'], keyPhrases:['enjoys sports','whereas','prefers reading'], functionTag:'comparison_whereas', topicTag:'writing', difficulty:3 },
  { sentence:'While the first method is quick, the second is more accurate.', sentenceZh:'第一种方法快，而第二种更准确。', chunkList:['While','the first method is quick',',','the second is','more accurate','.'], keyPhrases:['While','first method','second','more accurate'], functionTag:'comparison_while', topicTag:'writing', difficulty:3 },
  { sentence:'She is outgoing, whereas her sister is shy.', sentenceZh:'她很外向，而她妹妹很害羞。', chunkList:['She is outgoing',',','whereas','her sister is','shy','.'], keyPhrases:['outgoing','whereas','shy'], functionTag:'comparison_whereas', topicTag:'writing', difficulty:3 },
  { sentence:'While technology has advantages, it also has disadvantages.', sentenceZh:'虽然技术有优点，但也有缺点。', chunkList:['While','technology has advantages',',','it also has','disadvantages','.'], keyPhrases:['While','advantages','disadvantages'], functionTag:'comparison_while', topicTag:'writing', difficulty:3 },
  { sentence:'The north is cold, whereas the south is warm.', sentenceZh:'北方寒冷，而南方温暖。', chunkList:['The north is cold',',','whereas','the south is','warm','.'], keyPhrases:['north','cold','whereas','south','warm'], functionTag:'comparison_whereas', topicTag:'writing', difficulty:3 },
  { sentence:'While I understand your point, I still disagree.', sentenceZh:'虽然我理解你的观点，但我仍然不同意。', chunkList:['While','I understand your point',',','I still disagree','.'], keyPhrases:['While','understand','still disagree'], functionTag:'comparison_while', topicTag:'speaking', difficulty:3 },
  { sentence:'Public transport is cheap, whereas taxis are expensive.', sentenceZh:'公共交通便宜，而出租车贵。', chunkList:['Public transport is cheap',',','whereas','taxis are','expensive','.'], keyPhrases:['Public transport','cheap','whereas','taxis','expensive'], functionTag:'comparison_whereas', topicTag:'writing', difficulty:3 },
  { sentence:'While the idea is good, the execution needs work.', sentenceZh:'虽然想法很好，但执行需要改进。', chunkList:['While','the idea is good',',','the execution needs','work','.'], keyPhrases:['While','idea','good','execution','work'], functionTag:'comparison_while', topicTag:'writing', difficulty:3 },
  
  // Compared to
  { sentence:'Compared to last year, prices have risen.', sentenceZh:'与去年相比，价格上涨了。', chunkList:['Compared to','last year',',','prices have risen','.'], keyPhrases:['Compared to','last year','prices risen'], functionTag:'comparison_compared', topicTag:'writing', difficulty:3 },
  { sentence:'Life in the city is busy compared to life in the countryside.', sentenceZh:'与乡村生活相比，城市生活很繁忙。', chunkList:['Life in the city','is busy','compared to','life in the countryside','.'], keyPhrases:['Life in the city','busy','compared to','countryside'], functionTag:'comparison_compared', topicTag:'writing', difficulty:3 },
  { sentence:'Compared to other brands, this one is more reliable.', sentenceZh:'与其他品牌相比，这个更可靠。', chunkList:['Compared to','other brands',',','this one is','more reliable','.'], keyPhrases:['Compared to','other brands','more reliable'], functionTag:'comparison_compared', topicTag:'writing', difficulty:3 },
  { sentence:'The new model is lighter compared to the old one.', sentenceZh:'与旧型号相比，新型号更轻。', chunkList:['The new model','is lighter','compared to','the old one','.'], keyPhrases:['new model','lighter','compared to','old one'], functionTag:'comparison_compared', topicTag:'writing', difficulty:3 },
  { sentence:'Compared to walking, cycling is much faster.', sentenceZh:'与步行相比，骑自行车快得多。', chunkList:['Compared to','walking',',','cycling is','much faster','.'], keyPhrases:['Compared to','walking','cycling','much faster'], functionTag:'comparison_compared', topicTag:'writing', difficulty:3 },
  { sentence:'Her English is excellent compared to mine.', sentenceZh:'与我的相比，她的英语很棒。', chunkList:['Her English','is excellent','compared to','mine','.'], keyPhrases:['English','excellent','compared to','mine'], functionTag:'comparison_compared', topicTag:'speaking', difficulty:3 },
  { sentence:'Compared to summer, winter is much colder.', sentenceZh:'与夏天相比，冬天冷得多。', chunkList:['Compared to','summer',',','winter is','much colder','.'], keyPhrases:['Compared to','summer','winter','much colder'], functionTag:'comparison_compared', topicTag:'writing', difficulty:3 },
  { sentence:'The quality is better compared to what we had before.', sentenceZh:'与我们之前拥有的相比，质量更好。', chunkList:['The quality','is better','compared to','what we had before','.'], keyPhrases:['quality','better','compared to','before'], functionTag:'comparison_compared', topicTag:'writing', difficulty:3 },
  { sentence:'Compared to his brother, he is more serious.', sentenceZh:'与他弟弟相比，他更严肃。', chunkList:['Compared to','his brother',',','he is','more serious','.'], keyPhrases:['Compared to','his brother','more serious'], functionTag:'comparison_compared', topicTag:'speaking', difficulty:3 },
  { sentence:'This method is simpler compared to the traditional approach.', sentenceZh:'与传统方法相比，这种方法更简单。', chunkList:['This method','is simpler','compared to','the traditional approach','.'], keyPhrases:['method','simpler','compared to','traditional approach'], functionTag:'comparison_compared', topicTag:'writing', difficulty:3 },
  
  // On the one hand / On the other hand
  { sentence:'On the one hand, it\'s a great opportunity.', sentenceZh:'一方面，这是一个很好的机会。', chunkList:['On the one hand',',','it\'s','a great opportunity','.'], keyPhrases:['On the one hand','great opportunity'], functionTag:'comparison_contrast', topicTag:'writing', difficulty:3 },
  { sentence:'On the other hand, it requires a lot of time.', sentenceZh:'另一方面，它需要很多时间。', chunkList:['On the other hand',',','it requires','a lot of time','.'], keyPhrases:['On the other hand','requires','a lot of time'], functionTag:'comparison_contrast', topicTag:'writing', difficulty:3 },
  { sentence:'On the one hand, living in a city is convenient.', sentenceZh:'一方面，住在城市很方便。', chunkList:['On the one hand',',','living in a city','is convenient','.'], keyPhrases:['On the one hand','living in a city','convenient'], functionTag:'comparison_contrast', topicTag:'writing', difficulty:3 },
  { sentence:'On the other hand, it can be expensive.', sentenceZh:'另一方面，它可能很贵。', chunkList:['On the other hand',',','it can be','expensive','.'], keyPhrases:['On the other hand','can be','expensive'], functionTag:'comparison_contrast', topicTag:'writing', difficulty:3 },
  { sentence:'On the one hand, technology makes life easier.', sentenceZh:'一方面，技术让生活更轻松。', chunkList:['On the one hand',',','technology makes','life easier','.'], keyPhrases:['On the one hand','technology','makes life easier'], functionTag:'comparison_contrast', topicTag:'writing', difficulty:3 },
  { sentence:'On the other hand, it can be distracting.', sentenceZh:'另一方面，它可能会分散注意力。', chunkList:['On the other hand',',','it can be','distracting','.'], keyPhrases:['On the other hand','can be','distracting'], functionTag:'comparison_contrast', topicTag:'writing', difficulty:3 },
  { sentence:'On the one hand, working from home is flexible.', sentenceZh:'一方面，在家工作很灵活。', chunkList:['On the one hand',',','working from home','is flexible','.'], keyPhrases:['On the one hand','working from home','flexible'], functionTag:'comparison_contrast', topicTag:'writing', difficulty:3 },
  { sentence:'On the other hand, it can be isolating.', sentenceZh:'另一方面，它可能会让人感到孤立。', chunkList:['On the other hand',',','it can be','isolating','.'], keyPhrases:['On the other hand','can be','isolating'], functionTag:'comparison_contrast', topicTag:'writing', difficulty:3 },
  { sentence:'On the one hand, studying abroad is exciting.', sentenceZh:'一方面，出国留学很令人兴奋。', chunkList:['On the one hand',',','studying abroad','is exciting','.'], keyPhrases:['On the one hand','studying abroad','exciting'], functionTag:'comparison_contrast', topicTag:'writing', difficulty:3 },
  { sentence:'On the other hand, it can be challenging.', sentenceZh:'另一方面，它可能很有挑战性。', chunkList:['On the other hand',',','it can be','challenging','.'], keyPhrases:['On the other hand','can be','challenging'], functionTag:'comparison_contrast', topicTag:'writing', difficulty:3 },
];